### ISSUE TITLE
ETP-763 Missing Docker Compose Definition Causes smartbuild Task Failure on First Execution

### ISSUE THREAD

**Issue by isaiasb-etendo** [etendosoftware/com.etendoerp.platform.extensions#26]
# Error's Description

When I execute the smartbuild task for the first time, it fails because it tries to launch the container and the docker compose definition is missing.

# Steps to Reproduce the Error

1. Add a module with dockerization.

2. Set the docker-related variable associated with the service to true.

3. Run update.database smartbuild to install the module.

# Expected Behavior

The build should complete without errors, and the container should be running.

# Affected Version

`com.etendoerp.docker` version `1.5.0`

# Solution Design (optional)

Modify the smartbuild task or ensure generateEnvFile runs before any Gradle task execution.

# Other Test Cases

**Given:** An environment with modules that require dockerization.
**When:** Any Gradle task that depends on the docker infrastructure is executed.
**Then:** The generateEnvFile task should automatically be executed, ensuring the docker compose definition is available.

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [2.5.1](https://github.com/etendosoftware/com.etendoerp.platform.extensions/releases/tag/2.5.1) ⚡ 🚀
